#!/bin/bash


#
# Global Dependencies
#

echo "Checking global dependencies..."

if ! [[ `which bundle` ]]; then
  echo "Command 'bundle' not found. Please, install 'Bundler' gem first:"
  echo "  gem install bundler"

  exit 1
fi

if ! [[ `which bower` ]]; then
  echo "Command 'bower' not found. Please install 'Bower' first:"
  echo "  npm install bower -g"
  
  exit 1
fi

if ! [[ `which gulp` ]]; then
  echo "Command 'gulp' not found. Please install 'Gulp' first:"
  echo "  npm install gulp -g"

  exit 1
fi


#
# Project
#

echo "Configuring project..."
echo -n "Enter project name: "
read projectname

if [[ -f "bower.json" ]]; then
  rm "bower.json"
fi

if [[ -f "package.json" ]]; then
  rm "package.json"
fi

echo "{
  \"name\": \"$projectname\"
}" >> "bower.json"

echo "{
  \"name\": \"$projectname\",
  \"scripts\": {
    \"preinstall\": \"bundle\",
    \"postinstall\": \"bower install\",
    \"start\": \"gulp\"
  }
}" >> "package.json"

npm_dependencies=(
  gulp
  gulp-compass
  gulp-concat
  gulp-connect
  gulp-html2js
  gulp-plumber
  gulp-processhtml
  gulp-util
)

bower_dependencies=(
  angular
)

echo "installing dependencies..."
npm install --save ${npm_dependencies[@]}
bower install --save ${bower_dependencies[@]}

npm install

exit 0
